server:
  port: 9007
  address: localhost

ribbon:
  http:
    client:
      enabled: true

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/weshop
    username: root
    password: admin
    tomcat:
      initialSize: 1
      maxActive: 2
      connectionProperties: logger=com.mysql.jdbc.log.Slf4JLogger
  jpa:
    database: MYSQL
    hibernate:
      use-new-id-generator-mappings: false