server:
  port: ${SECURITY_SERVICE_PORT}

ribbon:
  http:
    client:
      enabled: true

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URLS}

spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    tomcat:
      connectionProperties: logger=com.mysql.jdbc.log.Slf4JLogger
  jpa:
    database: MYSQL
    hibernate:
      use-new-id-generator-mappings: false