/*
 * Copyright RepCar AD 2017
 */
package com.repcar.product.beans;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Company generated by hbm2java
 */
@Entity
public class Company {

    private Long companyId;
    private String companyName;
    private String companyAddress;

    @JsonCreator
    public Company() {
    }

    @JsonCreator
    public Company(@JsonProperty("companyName") String companyName,
            @JsonProperty("companyAddress") String companyAddress, @JsonProperty("shops") Set<Shop> shops,
            @JsonProperty("products") Set<Product> products) {
        this.companyName = companyName;
        this.companyAddress = companyAddress;
    }

    @Id
    @GeneratedValue
    @Column(unique = true, nullable = false)
    public Long getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    @NotNull
    @Column(length = 45)
    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @NotNull
    @Column(length = 45)
    public String getCompanyAddress() {
        return this.companyAddress;
    }

    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((companyAddress == null) ? 0 : companyAddress.hashCode());
        result = prime * result + ((companyId == null) ? 0 : companyId.hashCode());
        result = prime * result + ((companyName == null) ? 0 : companyName.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Company other = (Company) obj;
        if (companyAddress == null) {
            if (other.companyAddress != null)
                return false;
        } else if (!companyAddress.equals(other.companyAddress))
            return false;
        if (companyId == null) {
            if (other.companyId != null)
                return false;
        } else if (!companyId.equals(other.companyId))
            return false;
        if (companyName == null) {
            if (other.companyName != null)
                return false;
        } else if (!companyName.equals(other.companyName))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return new StringBuilder().append("Company [companyId=").append(companyId).append(", companyName=")
                .append(companyName).append(", companyAddress=").append(companyAddress).append("]").toString();
    }

}
